AWSTemplateFormatVersion: 2010-09-09
Description: Main API Gateway resources for Schoepproject sites
Parameters:
  DomainName:
    Type: String
    AllowedPattern: "([a-zA-Z0-9]+\\.)*schoepproject.com"
    Description: Domain name that all resources should be created for
    Default: api.schoepproject.com
  HostedZoneId:
    Type: String
    Description: ID of the Hosted Zone that will contain DNS entries and validate the certificate
    Default: ZOZJO7VU8BJZE
Resources:
  GatewayCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
  GatewayDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref GatewayCertificate
      DomainName: !Ref DomainName
