AWSTemplateFormatVersion: 2010-09-09
Description: Main API Gateway resources for Schoepproject sites
Parameters:
  DomainName:
    Type: String
    AllowedPattern: "([a-zA-Z0-9]+\\.)*schoepproject.com"
    Description: Domain name that all resources should be created for
    Default: api.schoepproject.com
  HostedZoneId:
    Type: String
    Description: ID of the Hosted Zone that will contain DNS entries and validate the certificate
    Default: ZOZJO7VU8BJZE
Resources:
  GatewayCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
  GatewayDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref DomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref GatewayCertificate
          EndpointType: REGIONAL
Outputs:
  GatewayDomainName:
    Description: Domain name for the created API
    Value: !Ref GatewayDomain
    Export:
      Name: !Sub "${AWS::StackName}-Domain-Name"
